language: go

go:
  - 1.8.x
  - 1.9.x

before_install: go get -u github.com/golang/dep/cmd/dep

install: 
  - dep ensure

script: make build-local

deploy:
  skip_cleanup: true
  provider: script
  script: maaii-zk-janitor --help
  on:
    tags: true
    all_branches: true
